### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/skill-ovos-pairing#76]
this skill has been evolving to become more and more like a OS first setup installer, kinda like Calamares

please discuss what direction you would like this skill to go here

- [x] default to offline usage, no backend needed
- [x] remove voice route, if wanted that should be it's own skill with different constraints
- [ ] add desktop file, so users can start setup anytime from GUI
- [ ] add standalone launcher script, so one can fully configure ovos without it running
    - [x] standalone skills now supported in ovos-workshop
- [x] optional stage in first boot (enabled via ready_settings in mycroft.conf)
- [ ] enable lang selection menu by default  (currently behind skill settings)
- [ ] enable backend selection menu #64 
- [ ] add voice intents for setting some config values

relevant discussions:
- https://github.com/OpenVoiceOS/skill-ovos-setup/issues/56
- https://github.com/OpenVoiceOS/skill-ovos-setup/issues/63

![imagem](https://github.com/OpenVoiceOS/skill-ovos-setup/assets/33701864/fe29e3a1-a58d-42ad-bc32-42dca4ba6d00)

![imagem](https://github.com/OpenVoiceOS/skill-ovos-setup/assets/33701864/cccc1139-af5b-437d-9734-1503656a3c3e)

![imagem](https://github.com/OpenVoiceOS/skill-ovos-setup/assets/33701864/bd5eab14-ad82-4e45-a41f-9fcd5ad88db4)

**Comment by j1nx** [comment]
Nothing to add, however to elaborate on "add voice intents for setting some config values";

- Set STT to VOSK, Whisper, etc (whatever is installed)
- Set TTS to ..... (ditto)

And perhaps for the above the addition of language setup for them.
